DROP PROCEDURE IF EXISTS `inc_flags`;
DELIMITER //
CREATE PROCEDURE `inc_flags`(IN `userID` INT)
BEGIN
SET @COUNT_FLAGS = (SELECT RATING_FLAGS FROM USERINFO WHERE USER_ID=userID) + 1;
UPDATE USERINFO SET RATING_FLAGS = @COUNT_FLAGS WHERE USER_ID=userID;

IF @COUNT_FLAGS = 3 OR @COUNT_FLAGS = 6 THEN
   SET @SPAM_COUNT = (SELECT SPAM_COUNT FROM USERINFO WHERE USER_ID=userID) + 1;
   UPDATE USERINFO SET SPAM_COUNT= @SPAM_COUNT WHERE USER_ID=userID;
END IF;
END//
DELIMITER ;