DROP PROCEDURE IF EXISTS `inc_warn`;
DELIMITER //
CREATE PROCEDURE `inc_warn`(IN `userID` INT)
BEGIN
SET @COUNT_WARN = (SELECT WARNINGS FROM USERINFO WHERE USER_ID=userID);
SET @COUNT_SPAM = (SELECT SPAM_COUNT FROM USERINFO WHERE USER_ID=userID);
UPDATE USERINFO SET WARNINGS=@COUNT_WARN+1 WHERE USER_ID=userID;
UPDATE USERINFO SET SPAM_COUNT=@COUNT_SPAM+1 WHERE USER_ID=userID;
END//
DELIMITER ;